spring.application.name=AirBnotB
spring.datasource.url=jdbc:mariadb://localhost:3306/AirBnotB
spring.datasource.username=lucatruant
spring.datasource.password=rauscedo
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=demo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
!--il segreto -->
app.jwt.secret=sposiamoci_giuseppe_rossi_ti_prego